# Generated by Django 3.2.7 on 2021-09-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
    ]
